#!/usr/bin/env python

from sys import argv
import numpy as np

args = argv[1:]
if len(args) != 2:
    print("Sample file and sobol coefficients (CSV) are required")
    exit(1)

sample_filename = args[0]
coefficient_filename = args[1]

samples = np.loadtxt(sample_filename, delimiter=",")
coefficients = np.loadtxt(coefficient_filename, delimiter=",")

num_parameters = samples.shape[1]
num_samples = samples.shape[0]

if len(coefficients) != num_parameters:
    raise Exception("Incorrect number of sobol coefficients")

coefficients_plus_1 = 1 + coefficients
for i in xrange(0, num_samples):
    print(np.prod(np.divide(abs(4 * samples[i, :] - 2) + coefficients,
                                    coefficients_plus_1)))
