#!/usr/bin/env python

from sys import argv
from getopt import getopt
from pyfast import freq


def print_usage():
    print("Usage: generate_samples [-h] <Number of Parameters>")
    print("Options:")
    print("-h, --help\t\tUsage instructions")

(opts, args) = getopt(argv[1:], "h", ["help", "delta_omega=", "omega="])

for (opt, optarg) in opts:
    while opt[0] == '-':
        opt = opt[1:]

    if opt in ["h", "help"]:
        print_usage()
        exit(0)
    elif opt == "delta_omega":
        delta_omega_file = optarg
    elif opt == "omega":
        omega_listfile = optarg

if len(args) != 1:
    from sys import stderr
    stderr.write("Missing number of parameters\n")
    stderr.write("For help, run generate_frequencies -h\n")
    exit(1)

num_params = int(args[0])

# Generate List
frequencies = freq(int(num_params))
print(",".join([str(i) for i in frequencies]))
